enabled: true
apiGroup: "monitoring.coreos.com"
image:
  repository: dockerhub.cyai.com/rancher/istio-kubectl
  tag: 1.1.5
resources:
  limits:
    cpu: 20m
    memory: 50Mi
  requests:
    cpu: 20m
    memory: 20Mi
