{
 "title": "App",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "label_values(mixin_pod_workload, namespace)"
   },
   {
    "name": "type",
    "label": "type",
    "query": "label_values(mixin_pod_workload{namespace=~\"$project\", workload=~\".+\"}, workload_type)"
   },
   {
    "name": "appname",
    "label": "appname",
    "query": "label_values(mixin_pod_workload{namespace=~\"$project\",workload_type=~\"$type\"}, workload)"
   }
  ]
 },
 "panels": [
  { "title": "App 概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment 副本数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$project.*\"}) "
    }
   ]
  },
  {
   "title": "Deployment 副本数-暂停",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_paused{namespace=~\"$project.*\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Deployment 副本数-不可用",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$project.*\"})"
    }
   ]
  },
  {
   "title": "StatefulSet 副本数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_statefulset_replicas{namespace=~\"$project\"})"
    }
   ]
  },
  {
   "title": "DaemonSet 副本数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_daemonset_metadata_generation{namespace=~\"$project.*\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$project\", phase=\"Running\"}) ",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$project.*\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$project.*\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$project.*\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "容器数量-运行中",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$project.*\"})"
    }
   ]
  },
  {
   "title": "容器数量-等待",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$project.*\"})"
    }
   ]
  },
  {
   "title": "容器数量-被终止",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$project.*\"})"
    }
   ]
  },
  {
   "title": "容器重启次数 (30/分钟)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=~\"$project.*\"}[30m]))"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$project.*\"})"
    }
   ]
  },
  {
   "title": "Jobs Active",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$project.*\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$project.*\"})"
    }
   ]
  },
  { "title": "App Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "App CPU 配额",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (workload, workload_type)"
    },
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests_cpu_cores{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n/sum(\n  kube_pod_container_resource_requests_cpu_cores{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits_cpu_cores{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n/sum(\n  kube_pod_container_resource_limits_cpu_cores{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n"
    }
   ]
  },
  {
   "title": "App CPU 使用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "App Memory 配额",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}) by (workload, workload_type)"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=~\"$project\", container!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests_memory_bytes{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=~\"$project\", container!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\",workload_type=\"$type\"}\n) by (workload, workload_type)\n/sum(\n  kube_pod_container_resource_requests_memory_bytes{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits_memory_bytes{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\", workload_type=\"$type\"}\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=~\"$project\", container!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\", workload_type=\"$type\"}\n) by (workload, workload_type)\n/sum(\n  kube_pod_container_resource_limits_memory_bytes{namespace=~\"$project\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\", workload_type=\"$type\"}\n) by (workload, workload_type)\n"
    }
   ]
  },
  {
   "title": "App Memory 使用大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=~\"$project\", container!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}\n) by (workload, workload_type)\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "App 当前 Network 状态",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{namespace=~\"$project\"}[5m])\n* on (namespace,pod)\ngroup_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}) by (workload))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{namespace=~\"$project\"}[5m])\n* on (namespace,pod)\ngroup_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}) by (workload))\n"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_total{namespace=~\"$project\"}[5m])\n* on (namespace,pod)\ngroup_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}) by (workload))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_total{namespace=~\"$project\"}[5m])\n* on (namespace,pod)\ngroup_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}) by (workload))\n"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$project\"}[5m])\n* on (namespace,pod)\ngroup_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}) by (workload))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$project\"}[5m])\n* on (namespace,pod)\ngroup_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}) by (workload))\n"
    }
   ]
  },
  {
   "title": "App 网络带宽",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{namespace=~\"$project\"}[5m])* on (namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\",workload=~\"$appname\", workload_type=\"$type\"}) by (workload))\n",
     "legendFormat": "- - -> {{workload}}"
    },
    {
     "expr": "- (sum(irate(container_network_transmit_bytes_total{namespace=~\"$project\"}[5m])* on (namespace,pod) group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (workload))",
     "legendFormat": "<- - - {{workload}}"
    }
   ]
  },
  {
   "title": "App 网络数据包",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (workload))",
     "legendFormat": "- - -> {{workload}}"
    },
    {
     "expr": "-(sum(irate(container_network_transmit_packets_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (workload))",
     "legendFormat": "<- - - {{workload}}"
    }
   ]
  },
  {
   "title": "App 丢包率",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$project\"}[5m])\n* on (namespace,pod)\ngroup_left(workload,workload_type) mixin_pod_workload{ namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (workload))\n",
     "legendFormat": "- - ->{{workload}}"
    },
    {
     "expr": "-(sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$project\"}[5m])\n* on (namespace,pod)\ngroup_left(workload,workload_type) mixin_pod_workload{ namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (workload))\n",
     "legendFormat": "<- - -{{workload}}"
    }
   ]
  },
  { "title": "Pods Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Pods CPU 配额",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods CPU 使用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Memory 配额",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$project\",container!=\"\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$project\",container!=\"\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$project\",container!=\"\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$project\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$project\",container!=\"\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$project\",container!=\"\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$project\",container!=\"\"}* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods Memory 使用",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$project\"} * on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Network 状态",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods 带宽",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod_name!=\"\",namespace=~\"$project.*\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)",
     "legendFormat": "- - ->{{pod}}"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{pod_name!=\"\",namespace=~\"$project.*\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)",
     "legendFormat": "<- - -{{pod}}"
    }
   ]
  },
  {
   "title": "Pods 数据包",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 116 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)",
     "legendFormat": "- - ->{{pod}}"
    },
    {
     "expr": "-sum(irate(container_network_transmit_packets_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)",
     "legendFormat": "<- - -{{pod}}"
    }
   ]
  },
  {
   "title": "Pods 丢包率",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 116 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)",
     "legendFormat": "- - ->{{pod}}"
    },
    {
     "expr": "-sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$project\"}[5m])* on (namespace,pod)group_left(workload,workload_type) mixin_pod_workload{namespace=~\"$project\", workload=~\"$appname\", workload_type=\"$type\"}) by (pod)",
     "legendFormat": "<- - -{{pod}}"
    }
   ]
  }
 ]
}