{
 "title": "Etcd",
 "description": "Etcd Dashboard for Prometheus metrics scraper",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Etcd仅有一个Leader ?",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "Leader变更次数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total)"
    }
   ]
  },
  {
   "title": "失败提议总次数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total)"
    }
   ]
  },
  {
   "title": "远程过程调用速率(RPC)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "活动流",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "数据库大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_debugging_mvcc_db_total_size_in_bytes)",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "磁盘同步时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "驻留内存大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}} Resident Memory" }
   ]
  },
  {
   "title": "GRPC流量接收",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total[5m]))",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "GRPC流量传输",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Raft 提议",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total[5m]))",
     "legendFormat": "提议失败"
    },
    {
     "expr": "sum(etcd_server_proposals_pending)",
     "legendFormat": "提议等待"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total[5m]))",
     "legendFormat": "提议提交"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total[5m]))",
     "legendFormat": "提议申请"
    }
   ]
  },
  {
   "title": "每日Leader选举频率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "The total number of consensus proposals committed",
   "type": "graph",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(increase(etcd_server_proposals_committed_total[5m]))",
     "legendFormat": "total number of consensus proposals committed"
    },
    {
     "expr": "sum(increase(etcd_server_proposals_applied_total[5m]))",
     "legendFormat": "total number of consensus proposals applied"
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "graph",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending)",
     "legendFormat": "Proposals pending"
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(etcd_disk_wal_fsync_duration_seconds_sum[5m]))",
     "legendFormat": " The latency distributions of fsync called by wal"
    },
    {
     "expr": "sum(increase(etcd_disk_backend_commit_duration_seconds_sum[5m]))",
     "legendFormat": "The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total[5m]))",
     "legendFormat": "The total number of bytes received by grpc clients"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total[5m]))",
     "legendFormat": "The total number of bytes sent to grpc clients"
    }
   ]
  },
  {
   "title": "Snapshot duration",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum[5m]))",
     "legendFormat": "The total latency distributions of save called by snapshot"
    }
   ]
  }
 ]
}