{
 "title": "Nodes",
 "description": "Nearly all default values exported by Prometheus node exporter graphed.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_load1, instance)"
   },
   {
    "name": "name",
    "query": "label_values(node_load1{instance=\"$node\"},node)"
   }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "运行时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"^$node\"} - node_boot_time_seconds{instance=~\"^$node\"}"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\",instance=~\"^$node\"})"
    },
    {
     "expr": "wmi_cs_logical_processors{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "总内存",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"^$node\"}"
    }
   ]
  },
  {
   "title": "Root磁盘容量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 15, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",instance=~\"^$node\"})"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"^$node\"}[5m])) by (instance))) * 100"
    }
   ]
  },
  {
   "title": "Memory使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"^$node\"} * 100) / node_memory_MemTotal_bytes{instance=~\"^$node\"})"
    }
   ]
  },
  {
   "title": "CPU Load (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\"}) / count(node_cpu_seconds_total{mode=\"system\",instance=~\"^$node\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Load (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node\"}) / count(node_cpu_seconds_total{mode=\"system\",instance=~\"^$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Root磁盘使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",instance=~\"^$node\"})     - sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\",instance=~\"^$node\"})) / sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",instance=~\"^$node\"}) * 100"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU 单核使用率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - rate(node_cpu_seconds_total{job=\"expose-node-metrics\", mode=\"idle\", instance=\"$node\"}[5m]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"expose-node-metrics\", mode=\"idle\", instance=\"$node\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"^$node\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"^$node\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"^$node\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Memory 使用",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"^$node\"} - node_memory_MemFree_bytes{instance=~\"^$node\"} - (node_memory_Cached_bytes{instance=~\"^$node\"} + node_memory_Buffers_bytes{instance=~\"^$node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"^$node\"} + node_memory_Buffers_bytes{instance=~\"^$node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"^$node\"}",
     "legendFormat": "RAM Available"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"^$node\"} - node_memory_SwapFree_bytes{instance=~\"^$node\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory 栈",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"^$node\"} - node_memory_MemFree_bytes{instance=~\"^$node\"} - node_memory_Buffers_bytes{instance=~\"^$node\"} - node_memory_Cached_bytes{instance=~\"^$node\"} - node_memory_Slab_bytes{instance=~\"^$node\"} - node_memory_PageTables_bytes{instance=~\"^$node\"} - node_memory_SwapCached_bytes{instance=~\"^$node\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"^$node\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"^$node\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"^$node\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"^$node\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"^$node\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"^$node\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"^$node\"} - node_memory_SwapFree_bytes{instance=~\"^$node\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"^$node\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    },
    {
     "expr": "wmi_os_virtual_memory_bytes{instance=~\"$node\"} > 0",
     "legendFormat": "Virtual"
    },
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$node\"} > 0",
     "legendFormat": "Physical"
    },
    {
     "expr": "wmi_os_physical_memory_free_bytes{instance=~\"$node\"} > 0",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "磁盘空间使用量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"^$node\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"^$node\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "wmi_logical_disk_free_bytes{instance=~\"$node\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "文件系统可用容量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"^$node\",device!~\"HarddiskVolume.+\"}",
     "legendFormat": "{{device}} - Available"
    }
   ]
  },
  {
   "title": "磁盘读写速率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"^$node\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m])",
     "legendFormat": "{{device}} - Reads"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"^$node\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m])",
     "legendFormat": "{{device}} - Writes"
    }
   ]
  },
  {
   "title": "磁盘读写 IOps (已完成)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "{{device}} - Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "{{device}} - Writes"
    },
    {
     "expr": "irate(wmi_logical_disk_writes_total{instance=~\"$node\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m])",
     "legendFormat": "{{volume}} - Writes"
    },
    {
     "expr": "irate(wmi_logical_disk_reads_total{instance=~\"$node\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m])",
     "legendFormat": "{{volume}} - Reads"
    }
   ]
  },
  {
   "title": "磁盘读写 Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ms", "label": "Millisec. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"^$node\", device!~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{device}} - Read time ms"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"^$node\", device!~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{device}} - Write time ms"
    }
   ]
  },
  {
   "title": "磁盘读写 Merged",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "iops", "label": "I/Os" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_merged_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "{{device}} - Reads"
    },
    {
     "expr": "irate(node_disk_writes_merged_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "{{device}} - Writes"
    }
   ]
  },
  {
   "title": "文件描述符",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Files" }
   ],
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=~\"^$node\"}",
     "legendFormat": "最大可打开数量"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"^$node\"}",
     "legendFormat": "已打开数量"
    }
   ]
  },
  {
   "title": "不能打开文件数量(Error)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "node_textfile_scrape_error{instance=~\"^$node\"}",
     "legendFormat": "Textfile scrape error (1 = true)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "网络带宽",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "- - ->{{device}}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "<- - -{{device}}"
    }
   ]
  },
  {
   "title": "网络数据包",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "- - ->{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "<- - -{{device}} "
    }
   ]
  },
  {
   "title": "网络数据包丢包",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "- - ->{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "<- - -{{device}} "
    }
   ]
  },
  {
   "title": "网络数据包错误",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "- - ->{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"^$node\"}[5m])",
     "legendFormat": "<- - -{{device}}"
    }
   ]
  },
  { "title": "Sockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Sockstat TCP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "Sockets" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"^$node\"}",
     "legendFormat": "TCP_alloc - Allocated sockets"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"^$node\"}",
     "legendFormat": "TCP_inuse - Tcp sockets currently in use"
    },
    {
     "expr": "node_sockstat_TCP_mem{instance=~\"^$node\"}",
     "legendFormat": "TCP_mem - Used memory for tcp"
    },
    {
     "expr": "node_sockstat_TCP_orphan{instance=~\"^$node\"}",
     "legendFormat": "TCP_orphan - Orphan sockets"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"^$node\"}",
     "legendFormat": "TCP_tw - Sockets wating close"
    },
    {
     "expr": "wmi_tcp_connections_active{instance=~\"^$node\"}",
     "legendFormat": "TCP_active"
    },
    {
     "expr": "wmi_tcp_connections_established{instance=~\"^$node\"}",
     "legendFormat": "TCP_established"
    },
    {
     "expr": "wmi_tcp_connections_passive{instance=~\"^$node\"}",
     "legendFormat": "TCP_passive"
    },
    {
     "expr": "wmi_tcp_connections_reset{instance=~\"^$node\"}",
     "legendFormat": "TCP_reset"
    }
   ]
  },
  {
   "title": "Sockstat UDP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "Sockets" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_UDPLITE_inuse{instance=~\"^$node\"}",
     "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"^$node\"}",
     "legendFormat": "UDP_inuse - Udp sockets currently in use"
    },
    {
     "expr": "node_sockstat_UDP_mem{instance=~\"^$node\"}",
     "legendFormat": "UDP_mem - Used memory for udp"
    }
   ]
  },
  {
   "title": "Sockstat Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short", "label": "Sockets" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{instance=~\"^$node\"}",
     "legendFormat": "Sockets_used - Sockets currently in use"
    },
    {
     "expr": "wmi_tcp_connections_established{instance=~\"^$node\"}",
     "legendFormat": "Sockets_established"
    }
   ]
  },
  {
   "title": "Sockstat Memory Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_mem_bytes{instance=~\"^$node\"}",
     "legendFormat": "TCP_mem_bytes - "
    },
    {
     "expr": "node_sockstat_UDP_mem_bytes{instance=~\"^$node\"}",
     "legendFormat": "UDP_mem_bytes - "
    }
   ]
  }
 ]
}